export const COUNTRY_PREFIXES = [
  // GCC / Middle East
  { prefix: '971', country: 'UAE' },
  { prefix: '966', country: 'Saudi Arabia' },
  { prefix: '968', country: 'Oman' },
  { prefix: '974', country: 'Qatar' },
  { prefix: '973', country: 'Bahrain' },
  { prefix: '965', country: 'Kuwait' },
  { prefix: '972', country: 'Israel' },
  { prefix: '970', country: 'Palestine' },
  { prefix: '962', country: 'Jordan' },
  { prefix: '961', country: 'Lebanon' },
  { prefix: '963', country: 'Syria' },
  { prefix: '964', country: 'Iraq' },
  { prefix: '967', country: 'Yemen' },
  { prefix: '98', country: 'Iran' },
  { prefix: '994', country: 'Azerbaijan' },
  { prefix: '995', country: 'Georgia' },
  { prefix: '993', country: 'Turkmenistan' },
  { prefix: '992', country: 'Tajikistan' },
  { prefix: '996', country: 'Kyrgyzstan' },
  { prefix: '998', country: 'Uzbekistan' },
  { prefix: '90', country: 'Turkey' },
  { prefix: '374', country: 'Armenia' },

  // Africa
  { prefix: '212', country: 'Morocco' },
  { prefix: '213', country: 'Algeria' },
  { prefix: '216', country: 'Tunisia' },
  { prefix: '218', country: 'Libya' },
  { prefix: '20', country: 'Egypt' },
  { prefix: '249', country: 'Sudan' },
  { prefix: '251', country: 'Ethiopia' },
  { prefix: '254', country: 'Kenya' },
  { prefix: '255', country: 'Tanzania' },
  { prefix: '256', country: 'Uganda' },
  { prefix: '233', country: 'Ghana' },
  { prefix: '234', country: 'Nigeria' },
  { prefix: '27', country: 'South Africa' },
  { prefix: '221', country: 'Senegal' },
  { prefix: '225', country: 'Ivory Coast' },
  { prefix: '237', country: 'Cameroon' },

  // Europe
  { prefix: '44', country: 'UK' },
  { prefix: '33', country: 'France' },
  { prefix: '49', country: 'Germany' },
  { prefix: '39', country: 'Italy' },
  { prefix: '34', country: 'Spain' },
  { prefix: '31', country: 'Netherlands' },
  { prefix: '32', country: 'Belgium' },
  { prefix: '41', country: 'Switzerland' },
  { prefix: '43', country: 'Austria' },
  { prefix: '351', country: 'Portugal' },
  { prefix: '30', country: 'Greece' },
  { prefix: '353', country: 'Ireland' },
  { prefix: '46', country: 'Sweden' },
  { prefix: '47', country: 'Norway' },
  { prefix: '45', country: 'Denmark' },
  { prefix: '358', country: 'Finland' },
  { prefix: '48', country: 'Poland' },
  { prefix: '420', country: 'Czech Republic' },
  { prefix: '421', country: 'Slovakia' },
  { prefix: '36', country: 'Hungary' },
  { prefix: '40', country: 'Romania' },
  { prefix: '359', country: 'Bulgaria' },
  { prefix: '385', country: 'Croatia' },
  { prefix: '381', country: 'Serbia' },
  { prefix: '380', country: 'Ukraine' },
  { prefix: '370', country: 'Lithuania' },
  { prefix: '371', country: 'Latvia' },
  { prefix: '372', country: 'Estonia' },
  { prefix: '352', country: 'Luxembourg' },
  { prefix: '356', country: 'Malta' },
  { prefix: '357', country: 'Cyprus' },
  { prefix: '354', country: 'Iceland' },
  { prefix: '7', country: 'Russia' },

  // Americas
  { prefix: '1', country: 'USA/Canada' },
  { prefix: '52', country: 'Mexico' },
  { prefix: '55', country: 'Brazil' },
  { prefix: '54', country: 'Argentina' },
  { prefix: '56', country: 'Chile' },
  { prefix: '57', country: 'Colombia' },
  { prefix: '51', country: 'Peru' },
  { prefix: '58', country: 'Venezuela' },
  { prefix: '593', country: 'Ecuador' },
  { prefix: '595', country: 'Paraguay' },
  { prefix: '598', country: 'Uruguay' },

  // Asia / Pacific
  { prefix: '91', country: 'India' },
  { prefix: '92', country: 'Pakistan' },
  { prefix: '880', country: 'Bangladesh' },
  { prefix: '94', country: 'Sri Lanka' },
  { prefix: '977', country: 'Nepal' },
  { prefix: '93', country: 'Afghanistan' },
  { prefix: '86', country: 'China' },
  { prefix: '852', country: 'Hong Kong' },
  { prefix: '853', country: 'Macau' },
  { prefix: '886', country: 'Taiwan' },
  { prefix: '81', country: 'Japan' },
  { prefix: '82', country: 'South Korea' },
  { prefix: '65', country: 'Singapore' },
  { prefix: '60', country: 'Malaysia' },
  { prefix: '62', country: 'Indonesia' },
  { prefix: '63', country: 'Philippines' },
  { prefix: '66', country: 'Thailand' },
  { prefix: '84', country: 'Vietnam' },
  { prefix: '855', country: 'Cambodia' },
  { prefix: '856', country: 'Laos' },
  { prefix: '95', country: 'Myanmar' },
  { prefix: '61', country: 'Australia' },
  { prefix: '64', country: 'New Zealand' },
].sort((a, b) => b.prefix.length - a.prefix.length)

export function getCountryFromPhone(phone?: string | null): string {
  if (!phone) return 'Unknown'

  // Keep digits only, then strip international dial prefixes (00 / 011)
  let clean = phone.replace(/[^0-9]/g, '')
  if (clean.startsWith('00')) clean = clean.slice(2)
  else if (clean.startsWith('011')) clean = clean.slice(3)

  for (const entry of COUNTRY_PREFIXES) {
    if (clean.startsWith(entry.prefix)) return entry.country
  }
  return 'Unknown'
}
